[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200

; Build with RMT-based photoreflector implementation for improved edge capture
build_flags = -DUSE_RMT
